# Generated by Django 5.2.9 on 2026-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apppermission_role_agence_categorie_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['direction', 'niveau_acces', 'nom'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AddField(
            model_name='role',
            name='direction',
            field=models.CharField(blank=True, choices=[('Direction Commerciale', 'Direction Commerciale'), ('Direction des Achats', 'Direction des Achats'), ('Direction des Ressources Humaines', 'Direction des Ressources Humaines'), ('Direction de la Production', 'Direction de la Production'), ('Direction Logistique & Stock', 'Direction Logistique & Stock'), ('Direction Informatique', 'Direction Informatique'), ('Direction Juridique', 'Direction Juridique'), ('Direction des Projets', 'Direction des Projets')], max_length=50, null=True, verbose_name='Direction'),
        ),
    ]
