# Generated by Django 5.2.9 on 2026-06-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_role_options_role_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VIEW', 'Consultation')], max_length=20, verbose_name='Action')),
                ('content_type', models.CharField(max_length=100, verbose_name='Type de contenu')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Objet')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'objet")),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valeurs précédentes')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails supplémentaires')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_activi_timesta_8baae3_idx'), models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_d7adda_idx'), models.Index(fields=['content_type', '-timestamp'], name='core_activi_content_8de0e5_idx')],
            },
        ),
    ]
