# Generated by Django 5.2.9 on 2026-06-29 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='date_creation',
            field=models.DateField(default=datetime.date(2026, 6, 29), verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
