# Generated by Django 5.2.9 on 2026-06-29 21:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categorie_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateField(default=datetime.date(2026, 6, 29), verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.societe', verbose_name='Société'),
            preserve_default=False,
        ),
    ]
