# Generated by Django 5.2.9 on 2026-07-01 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produit_date_creation_produit_societe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societe',
            options={'ordering': ['raison_sociale'], 'verbose_name': 'Société', 'verbose_name_plural': 'Sociétés'},
        ),
        migrations.RemoveField(
            model_name='societe',
            name='code',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='societe',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='societe',
            name='code_societe',
            field=models.CharField(db_index=True, default='DEFAULT', max_length=20, unique=True, verbose_name='Code Société'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modification'),
        ),
        migrations.AddField(
            model_name='societe',
            name='forme_juridique',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forme Juridique'),
        ),
        migrations.AddField(
            model_name='societe',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='societe',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro Fiscal'),
        ),
        migrations.AddField(
            model_name='societe',
            name='numero_registre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro Registre'),
        ),
        migrations.AddField(
            model_name='societe',
            name='raison_sociale',
            field=models.CharField(default='SOCIETE', max_length=200, verbose_name='Raison Sociale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='site_web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Web'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddIndex(
            model_name='societe',
            index=models.Index(fields=['code_societe'], name='core_societ_code_so_8212b9_idx'),
        ),
        migrations.AddIndex(
            model_name='societe',
            index=models.Index(fields=['actif'], name='core_societ_actif_f95f5c_idx'),
        ),
    ]
