# Generated by Django 5.2.9 on 2026-07-01 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_societe_options_remove_societe_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'ordering': ['module', 'nom_permission'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='utilisateurprofile',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RenameField(
            model_name='apppermission',
            old_name='code',
            new_name='code_permission',
        ),
        migrations.RenameField(
            model_name='apppermission',
            old_name='nom',
            new_name='nom_permission',
        ),
        migrations.RemoveField(
            model_name='apppermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='utilisateurprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='utilisateurprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apppermission',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurprofile',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurprofile',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modification'),
        ),
        migrations.AddField(
            model_name='utilisateurprofile',
            name='email',
            field=models.EmailField(default='admin@default.com', max_length=100, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurprofile',
            name='nom',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurprofile',
            name='prenom',
            field=models.CharField(default='Super', max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='module',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='utilisateurprofile',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='utilisateurprofile',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière Connexion'),
        ),
        migrations.AlterField(
            model_name='utilisateurprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role', verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='utilisateurprofile',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='utilisateurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte auth'),
        ),
        migrations.AddIndex(
            model_name='utilisateurprofile',
            index=models.Index(fields=['societe', 'agence', 'actif'], name='core_utilis_societe_d3f234_idx'),
        ),
    ]
