# Generated by Django 5.2.9 on 2026-07-01 20:19

from django.db import migrations


def create_permissions(apps, schema_editor):
    """Créer les permissions pour tous les modules"""
    AppPermission = apps.get_model('core', 'AppPermission')
    
    permissions = [
        # Produits et Stock
        ('produit_voir', 'Voir les produits', 'Produits'),
        ('produit_ajouter', 'Ajouter un produit', 'Produits'),
        ('produit_modifier', 'Modifier un produit', 'Produits'),
        ('produit_supprimer', 'Supprimer un produit', 'Produits'),
        ('stock_voir', 'Voir le stock', 'Stock'),
        ('mouvement_ajouter', 'Ajouter un mouvement', 'Stock'),
        ('inventaire_voir', 'Voir les inventaires', 'Stock'),
        
        # Ventes
        ('vente_voir', 'Voir les ventes', 'Ventes'),
        ('facture_ajouter', 'Ajouter une facture', 'Ventes'),
        ('facture_modifier', 'Modifier une facture', 'Ventes'),
        ('facture_supprimer', 'Supprimer une facture', 'Ventes'),
        ('client_voir', 'Voir les clients', 'Ventes'),
        ('client_ajouter', 'Ajouter un client', 'Ventes'),
        
        # Achats
        ('achat_voir', 'Voir les achats', 'Achats'),
        ('achat_ajouter', 'Ajouter un achat', 'Achats'),
        ('achat_modifier', 'Modifier un achat', 'Achats'),
        ('achat_supprimer', 'Supprimer un achat', 'Achats'),
        ('fournisseur_voir', 'Voir les fournisseurs', 'Achats'),
        ('fournisseur_ajouter', 'Ajouter un fournisseur', 'Achats'),
        
        # Comptabilité
        ('ecriture_voir', 'Voir les écritures', 'Comptabilité'),
        ('ecriture_ajouter', 'Ajouter une écriture', 'Comptabilité'),
        ('ecriture_modifier', 'Modifier une écriture', 'Comptabilité'),
        ('ecriture_supprimer', 'Supprimer une écriture', 'Comptabilité'),
        ('journal_voir', 'Voir les journaux', 'Comptabilité'),
        ('plan_comptable_voir', 'Voir le plan comptable', 'Comptabilité'),
        ('rapport_comptable_voir', 'Voir les rapports comptables', 'Comptabilité'),
        
        # Contacts
        ('contact_voir', 'Voir les contacts', 'Contacts'),
        ('contact_ajouter', 'Ajouter un contact', 'Contacts'),
        ('contact_modifier', 'Modifier un contact', 'Contacts'),
        ('contact_supprimer', 'Supprimer un contact', 'Contacts'),
        
        # Paramètres
        ('utilisateur_voir', 'Voir les utilisateurs', 'Paramètres'),
        ('utilisateur_ajouter', 'Ajouter un utilisateur', 'Paramètres'),
        ('utilisateur_modifier', 'Modifier un utilisateur', 'Paramètres'),
        ('utilisateur_supprimer', 'Supprimer un utilisateur', 'Paramètres'),
        ('role_voir', 'Voir les rôles', 'Paramètres'),
        ('role_modifier', 'Modifier les rôles', 'Paramètres'),
        ('permission_modifier', 'Modifier les permissions', 'Paramètres'),
        ('societe_voir', 'Voir les sociétés', 'Paramètres'),
        ('societe_modifier', 'Modifier les sociétés', 'Paramètres'),
        ('agence_voir', 'Voir les agences', 'Paramètres'),
        ('agence_modifier', 'Modifier les agences', 'Paramètres'),
        
        # Statistiques
        ('statistique_voir', 'Voir les statistiques', 'Statistiques'),
        ('rapport_voir', 'Voir les rapports', 'Statistiques'),
    ]
    
    for code, nom, module in permissions:
        AppPermission.objects.get_or_create(
            code_permission=code,
            defaults={
                'nom_permission': nom,
                'module': module,
                'description': f'{nom} dans le module {module}'
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_apppermission_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
