# Generated by Django 6.0.6 on 2026-07-03 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _populate_produit_codes_and_names(apps, schema_editor):
    Produit = apps.get_model('core', 'Produit')

    for produit in Produit.objects.all().iterator():
        updates = []
        if not produit.code_produit:
            produit.code_produit = f"PROD-{produit.id:06d}"
            updates.append('code_produit')
        if not produit.nom_produit:
            produit.nom_produit = f"Produit {produit.id}"
            updates.append('nom_produit')
        if updates:
            produit.save(update_fields=updates)


def _populate_mouvement_utilisateur(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    MouvementStock = apps.get_model('core', 'MouvementStock')

    fallback_user = User.objects.order_by('id').first()
    if fallback_user is None:
        fallback_user = User.objects.create(
            username='system_migration',
            email='system@local',
            password='!',
            is_active=True,
        )

    valid_user_ids = set(User.objects.values_list('id', flat=True))
    for mouvement in MouvementStock.objects.all().iterator():
        if not mouvement.utilisateur_id or mouvement.utilisateur_id not in valid_user_ids:
            mouvement.utilisateur_id = fallback_user.id
            mouvement.save(update_fields=['utilisateur'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_fournisseur_model_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.IntegerField(default=0, verbose_name='Quantité disponible')),
                ('quantite_reservee', models.IntegerField(default=0, verbose_name='Quantité réservée')),
                ('valeur_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur stock')),
                ('date_dernier_mouvement', models.DateTimeField(blank=True, null=True, verbose_name='Date dernier mouvement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom_categorie'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['raison_sociale', 'nom', 'prenom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['raison_sociale'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom_produit'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='code',
            new_name='code_categorie',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='nom_categorie',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='remarque',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite_stock',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='core.categorie', verbose_name='Catégorie parente'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code client'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='client',
            name='condition_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condition de paiement'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='client',
            name='limite_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de crédit'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], default='Particulier', max_length=20, verbose_name='Type client'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code_fournisseur',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code fournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='condition_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condition de paiement'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro fiscal'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='raison_sociale',
            field=models.CharField(default='', max_length=200, verbose_name='Raison sociale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='agence_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_destination', to='core.agence', verbose_name='Agence destination'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code barre'),
        ),
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom produit'),
            preserve_default=False,
        ),
        migrations.RunPython(_populate_produit_codes_and_names, migrations.RunPython.noop),
        migrations.RunPython(_populate_mouvement_utilisateur, migrations.RunPython.noop),
        migrations.AddField(
            model_name='produit',
            name='prix_achat_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix achat HT'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix vente HT'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_alerte',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock alerte'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock maximum'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock minimum'),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA'),
        ),
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(choices=[('Bien', 'Bien'), ('Service', 'Service'), ('Consommable', 'Consommable')], default='Bien', max_length=20, verbose_name='Type produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(default='Unité', max_length=20, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='core.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert'), ('ajustement', 'Ajustement'), ('inventaire', 'Inventaire')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=200, verbose_name='Nom produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['societe'], name='core_catego_societe_fb2b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['societe', 'actif'], name='core_client_societe_3a78dd_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code_client'], name='core_client_code_cl_3f6dab_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['raison_sociale'], name='core_client_raison__f58476_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['societe', 'actif'], name='core_fourni_societe_128514_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['code_fournisseur'], name='core_fourni_code_fo_f2c780_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['raison_sociale'], name='core_fourni_raison__983e63_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['agence', 'date_mouvement'], name='core_mouvem_agence__5cd69e_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit'], name='core_mouvem_produit_c672dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='core_mouvem_type_mo_75d2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['societe'], name='core_produi_societe_b70334_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='core_produi_categor_99182b_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['actif'], name='core_produi_actif_6c6e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom_produit'], name='core_produi_nom_pro_381634_idx'),
        ),
        migrations.AddField(
            model_name='stock',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.produit', verbose_name='Produit'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['agence'], name='core_stock_agence__fe295b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('produit', 'agence')},
        ),
    ]
