# Generated by Django 6.0.6 on 2026-07-04 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stock_alter_categorie_options_alter_client_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC')),
                ('quantite_recue', models.IntegerField(default=0, verbose_name='Quantité reçue')),
            ],
            options={
                'verbose_name': 'Ligne achat',
                'verbose_name_plural': 'Lignes achat',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Remise')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC')),
            ],
            options={
                'verbose_name': 'Ligne vente',
                'verbose_name_plural': 'Lignes vente',
            },
        ),
        migrations.AlterModelOptions(
            name='achat',
            options={'ordering': ['-date_achat', 'numero_achat'], 'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_vente', 'numero_vente'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_ventes_achats(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='achat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_emission',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='achat',
            name='date_achat',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date achat'),
        ),
        migrations.AddField(
            model_name='achat',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='achat',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant restant'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='achat',
            name='numero_achat',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numéro achat'),
        ),
        migrations.AddField(
            model_name='achat',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='achat',
            name='statut_achat',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Validee', 'Validee'), ('Receptionnee', 'Receptionnee'), ('Annulee', 'Annulee')], default='Brouillon', max_length=20, verbose_name='Statut achat'),
        ),
        migrations.AddField(
            model_name='achat',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='core.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_vente',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date vente'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant restant'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_vente',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numéro vente'),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut_vente',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Validee', 'Validee'), ('Annulee', 'Annulee')], db_index=True, default='Brouillon', max_length=20, verbose_name='Statut vente'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_vente',
            field=models.CharField(choices=[('Comptant', 'Comptant'), ('Credit', 'Credit')], default='Comptant', max_length=20, verbose_name='Type vente'),
        ),
        migrations.AddField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['agence', 'date_achat'], name='core_achat_agence__6e57ff_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['fournisseur'], name='core_achat_fournis_373ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['agence', 'date_vente'], name='core_factur_agence__e8b3db_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut_vente', 'date_vente'], name='core_factur_statut__238b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client'], name='core_factur_client__58c320_idx'),
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_achat', to='core.achat', verbose_name='Achat'),
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achat', to='core.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='core.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='core.facture', verbose_name='Vente'),
        ),
        migrations.AddIndex(
            model_name='ligneachat',
            index=models.Index(fields=['achat'], name='core_lignea_achat_i_c3e4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lignevente',
            index=models.Index(fields=['vente'], name='core_lignev_vente_i_ae35ff_idx'),
        ),
    ]


def _backfill_ventes_achats(apps, schema_editor):
    Facture = apps.get_model('core', 'Facture')
    Achat = apps.get_model('core', 'Achat')
    User = apps.get_model('auth', 'User')
    Societe = apps.get_model('core', 'Societe')
    Agence = apps.get_model('core', 'Agence')

    default_user = User.objects.order_by('id').first()
    default_societe = Societe.objects.order_by('id').first()
    default_agence = Agence.objects.order_by('id').first()

    for facture in Facture.objects.order_by('id').all():
        if not facture.numero_vente:
            facture.numero_vente = facture.reference or f"V-{facture.pk}"
        if not facture.societe_id and default_societe:
            facture.societe_id = default_societe.id
        if not facture.agence_id and default_agence:
            facture.agence_id = default_agence.id
        if not facture.utilisateur_id and default_user:
            facture.utilisateur_id = default_user.id
        facture.montant_ht = facture.montant_ht or 0
        facture.montant_tva = facture.montant_tva or 0
        facture.montant_ttc = facture.montant_ttc or (facture.montant_total or 0)
        facture.remise = facture.remise or 0
        facture.montant_paye = facture.montant_paye or 0
        facture.montant_restant = facture.montant_restant or 0
        facture.statut_vente = getattr(facture, 'statut_vente', None) or 'Brouillon'
        if hasattr(facture, 'date_emission') and facture.date_emission:
            facture.date_vente = facture.date_emission
        if hasattr(facture, 'created_at') and facture.created_at:
            facture.date_creation = facture.created_at
        if hasattr(facture, 'updated_at') and facture.updated_at:
            facture.date_modification = facture.updated_at
        facture.save()

    for achat in Achat.objects.order_by('id').all():
        if not achat.numero_achat:
            achat.numero_achat = achat.reference or f"A-{achat.pk}"
        if not achat.societe_id and default_societe:
            achat.societe_id = default_societe.id
        if not achat.agence_id and default_agence:
            achat.agence_id = default_agence.id
        if not achat.utilisateur_id and default_user:
            achat.utilisateur_id = default_user.id
        achat.montant_ht = achat.montant_ht or 0
        achat.montant_tva = achat.montant_tva or 0
        achat.montant_ttc = achat.montant_ttc or (achat.montant_total or 0)
        achat.montant_paye = achat.montant_paye or 0
        achat.montant_restant = achat.montant_restant or 0
        achat.statut_achat = getattr(achat, 'statut_achat', None) or 'Brouillon'
        if hasattr(achat, 'date_commande') and achat.date_commande:
            achat.date_achat = achat.date_commande
        if hasattr(achat, 'created_at') and achat.created_at:
            achat.date_creation = achat.created_at
        achat.save()
