# Generated by Django 6.0.6 on 2026-07-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ligneachat_lignevente_alter_achat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='core.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='achat',
            name='type_achat',
            field=models.CharField(choices=[('Produit', 'Produit'), ('Service', 'Service'), ('Travaux', 'Travaux')], default='Produit', max_length=20, verbose_name='Type achat'),
        ),
        migrations.AddField(
            model_name='facture',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='core.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Désignation'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_vente',
            field=models.CharField(choices=[('Produit', 'Produit'), ('Service', 'Service'), ('Travaux', 'Travaux')], default='Comptant', max_length=20, verbose_name='Type vente'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achat', to='core.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='core.produit', verbose_name='Produit'),
        ),
    ]
