# Generated by Django 6.0.6 on 2026-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projet_schema_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projet',
            new_name='core_projet_societe_6bc820_idx',
            old_name='core_projet_soc_idx',
        ),
        migrations.RenameIndex(
            model_name='projet',
            new_name='core_projet_client__e40484_idx',
            old_name='core_projet_cli_idx',
        ),
        migrations.RenameIndex(
            model_name='projet',
            new_name='core_projet_statut__969f47_idx',
            old_name='core_projet_sta_idx',
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_previsionnel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Budget prévisionnel'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin prévue'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='libelle_projet',
            field=models.CharField(max_length=200, verbose_name='Libellé projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='reference_projet',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence projet'),
        ),
    ]
