# Generated by Django 6.0.6 on 2026-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_core_projet_soc_idx_core_projet_societe_6bc820_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='libelle_projet',
            field=models.CharField(max_length=200, verbose_name='LibelleProjet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='reference_projet',
            field=models.CharField(max_length=50, unique=True, verbose_name='ReferenceProjet'),
        ),
    ]
