# Generated by Django 6.0.6 on 2026-07-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_projet_libelle_projet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_caisse', models.CharField(max_length=20, unique=True, verbose_name='Code caisse')),
                ('nom_caisse', models.CharField(max_length=100, verbose_name='Nom caisse')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde initial')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde actuel')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='core.agence', verbose_name='Agence')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses_responsable', to='core.utilisateurprofile', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['nom_caisse'],
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('table_cible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Table cible')),
                ('enregistrement_id', models.BigIntegerField(blank=True, null=True, verbose_name='Enregistrement ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('adresse_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date action')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_activite', to='core.utilisateurprofile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log activité',
                'verbose_name_plural': 'Logs activité',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('Entree', 'Entree'), ('Sortie', 'Sortie')], max_length=20, verbose_name='Type mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date mouvement')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='core.caisse', verbose_name='Caisse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_caisse', to='core.utilisateurprofile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement caisse',
                'verbose_name_plural': 'Mouvements caisse',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['agence'], name='core_caisse_agence__a1a7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='logactivite',
            index=models.Index(fields=['utilisateur', 'date_action'], name='core_logact_utilisa_10d097_idx'),
        ),
        migrations.AddIndex(
            model_name='logactivite',
            index=models.Index(fields=['table_cible'], name='core_logact_table_c_71dec4_idx'),
        ),
        migrations.AddIndex(
            model_name='logactivite',
            index=models.Index(fields=['date_action'], name='core_logact_date_ac_bf22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['caisse', 'date_mouvement'], name='core_mouvem_caisse__be7e1f_idx'),
        ),
    ]
