# Generated by Django 6.0.6 on 2026-07-04 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_caisse_logactivite_mouvementcaisse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_banque', models.CharField(max_length=20, unique=True, verbose_name='Code banque')),
                ('nom_banque', models.CharField(max_length=100, verbose_name='Nom banque')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde initial')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde actuel')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banques', to='core.agence', verbose_name='Agence')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banques_responsable', to='core.utilisateurprofile', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['nom_banque'],
            },
        ),
        migrations.CreateModel(
            name='MouvementBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('Entree', 'Entree'), ('Sortie', 'Sortie')], max_length=20, verbose_name='Type mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date mouvement')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_banque', to='core.banque', verbose_name='Banque')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_banque', to='core.utilisateurprofile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement banque',
                'verbose_name_plural': 'Mouvements banque',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddIndex(
            model_name='banque',
            index=models.Index(fields=['agence'], name='core_banque_agence__43908a_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementbanque',
            index=models.Index(fields=['banque', 'date_mouvement'], name='core_mouvem_banque__07b1df_idx'),
        ),
    ]
