# Generated by Django 6.0.6 on 2026-07-04 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_banque_mouvementbanque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(blank=True, null=True, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Crédit')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Ligne écriture',
                'verbose_name_plural': 'Lignes écritures',
            },
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True, verbose_name='Numéro compte')),
                ('nom_compte', models.CharField(max_length=200, verbose_name='Nom compte')),
                ('type_compte', models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Charge', 'Charge'), ('Produit', 'Produit'), ('Resultat', 'Resultat')], max_length=20, verbose_name='Type compte')),
                ('classe', models.IntegerField(verbose_name='Classe')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Plan comptable',
                'verbose_name_plural': 'Plan comptable',
                'ordering': ['numero_compte'],
            },
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='core.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='libelle_ecriture',
            field=models.TextField(blank=True, null=True, verbose_name='Libellé écriture'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='numero_ecriture',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro écriture'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece_comptable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pièce comptable'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.utilisateurprofile', verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='journal',
            name='type_journal',
            field=models.CharField(choices=[('Achat', 'Achat'), ('Vente', 'Vente'), ('Banque', 'Banque'), ('Caisse', 'Caisse'), ('OD', 'OD')], default='OD', max_length=20, verbose_name='Type journal'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['agence', 'date_ecriture'], name='core_ecritu_agence__3eeb21_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['journal'], name='core_ecritu_journal_dfcf18_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['societe'], name='core_journa_societe_670777_idx'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='ecriture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.ecriturecomptable', verbose_name='Écriture'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='compte_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='core.plancomptable', verbose_name='Compte parent'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_comptables', to='core.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='core.plancomptable', verbose_name='Compte'),
        ),
        migrations.AddIndex(
            model_name='plancomptable',
            index=models.Index(fields=['societe', 'numero_compte'], name='core_planco_societe_e4eac7_idx'),
        ),
        migrations.AddIndex(
            model_name='plancomptable',
            index=models.Index(fields=['type_compte'], name='core_planco_type_co_347923_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['ecriture'], name='core_lignee_ecritur_a29493_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['compte'], name='core_lignee_compte__368cf3_idx'),
        ),
    ]
