# Generated by Django 6.0.6 on 2026-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ligneecriture_plancomptable_ecriturecomptable_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomptable',
            name='numero_compte',
            field=models.CharField(max_length=20, verbose_name='Numéro compte'),
        ),
        migrations.AddConstraint(
            model_name='plancomptable',
            constraint=models.UniqueConstraint(fields=('societe', 'numero_compte'), name='uniq_plancomptable_societe_numero'),
        ),
    ]
