# Generated by Django 6.0.6 on 2026-07-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_plancomptable_numero_compte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptabilisationParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equilibre_obligatoire', models.BooleanField(default=True, verbose_name='Équilibre débit/crédit obligatoire')),
                ('numerotation_auto', models.BooleanField(default=True, verbose_name='Numérotation automatique des écritures')),
                ('verrouillage_periode', models.BooleanField(default=False, verbose_name='Contrôle de période comptable')),
                ('champs_facultatifs_actifs', models.BooleanField(default=True, verbose_name='Activer les champs facultatifs')),
                ('modeles_recurrents_actifs', models.BooleanField(default=False, verbose_name="Activer les modèles d'écriture récurrents")),
                ('mode_annulation', models.CharField(choices=[('contrepassation', 'Contrepassation automatique'), ('suppression', 'Suppression avec trace')], default='contrepassation', max_length=20, verbose_name="Mode d'annulation")),
                ('motif_annulation_obligatoire', models.BooleanField(default=True, verbose_name="Motif d'annulation obligatoire")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('journal_defaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_par_defaut', to='core.journal', verbose_name='Journal par défaut')),
                ('roles_autorises_annulation', models.ManyToManyField(blank=True, related_name='parametres_annulation', to='core.role', verbose_name='Rôles autorisés à annuler')),
                ('societe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_comptabilisation', to='core.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paramètre de comptabilisation',
                'verbose_name_plural': 'Paramètres de comptabilisation',
                'ordering': ['societe__raison_sociale'],
            },
        ),
    ]
