# Generated by Django 6.0.6 on 2026-07-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_comptabilisationparametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptabilisationparametre',
            name='type_numerotation',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('continue_journal', 'Continue par journal')], default='mensuel', max_length=20, verbose_name='Type de numérotation'),
        ),
        migrations.AddField(
            model_name='journal',
            name='compte_defaut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_par_defaut', to='core.plancomptable', verbose_name='Compte par défaut'),
        ),
        migrations.AddField(
            model_name='journal',
            name='type_numerotation',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('continue_journal', 'Continue par journal')], default='mensuel', max_length=20, verbose_name='Type de numérotation'),
        ),
    ]
