# Generated by Django 6.0.6 on 2026-07-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_comptabilisationparametre_type_numerotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
