# Generated by Django 6.0.6 on 2026-07-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ecriturecomptable_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptabilisationparametre',
            name='compte_tiers_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_tiers_client', to='core.plancomptable', verbose_name='Compte tiers client'),
        ),
        migrations.AddField(
            model_name='comptabilisationparametre',
            name='compte_tiers_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_tiers_fournisseur', to='core.plancomptable', verbose_name='Compte tiers fournisseur'),
        ),
    ]
