# Generated by Django 6.0.6 on 2026-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_comptabilisationparametre_compte_tiers_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptabilisationparametre',
            name='racine_numero_ecriture',
            field=models.CharField(default='ECR', max_length=20, verbose_name='Racine numéro écriture'),
        ),
    ]
