# Generated by Django 6.0.6 on 2026-07-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_comptabilisationparametre_racine_numero_ecriture'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='racine_numero_ecriture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Racine numéro écriture'),
        ),
    ]
