# Generated by Django 6.0.6 on 2026-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_journal_racine_numero_ecriture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomptable',
            name='type_compte',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Charge', 'Charge'), ('Produit', 'Produit'), ('Resultat', 'Resultat'), ('Actifs circulants', 'Actifs circulants'), ('Actifs immobilisés', 'Actifs immobilisés'), ('Autres produits', 'Autres produits'), ('Banque et espèces', 'Banque et espèces'), ("Bénéfices de l'exercice en cours", "Bénéfices de l'exercice en cours"), ('Capitaux propres', 'Capitaux propres'), ('Charges', 'Charges'), ('Client', 'Client'), ('Dettes à court terme', 'Dettes à court terme'), ('Fournisseur', 'Fournisseur'), ('Hors bilan', 'Hors bilan'), ('Revenus', 'Revenus')], max_length=50, verbose_name='Type compte'),
        ),
    ]
